export enum Op {
  Konstanta,
  Kosong,
  Taktentu,
  Benar,
  Salah,
  Nol,
  Satu,

  Pop,
  Gandakan,
  Gandakan2,
  Tukar,

  TambahLokal,
  BacaLokal,
  TulisLokal,
  BacaGlobal,
  TulisGlobal,
  DefinisiGlobal,
  BacaUpvalue,
  TulisUpvalue,
  TutupUpvalue,

  Tambah,
  Kurang,
  Kali,
  Bagi,
  Sisa,
  Pangkat,
  Negasi,
  Positif,

  Dan,
  Atau,
  Xor,
  Tilde,
  GeserKiri,
  GeserKanan,
  GeserKananNol,

  SamaDengan,
  TidakSama,
  KurangDari,
  LebihDari,
  KurangSamaDari,
  LebihSamaDari,

  Bukan,
  JenisDari,
  ContohDari,
  Dalam,

  Lompat,
  LompatJikaSalah,
  LompatJikaBenar,
  LompatBalik,

  Panggil,
  PanggilDenganIni,
  Penutup,
  Kembali,

  LompatJikaKosong,
  LompatJikaTaktentu,
  LarikSisa,

  KelasBaru,
  WarisiKelas,
  MetodeKelas,
  FieldInstance,
  FieldStatis,
  JalankanStatis,
  Konstruksi,
  PanggilInduk,
  BacaIndukMetode,
  SelesaikanKelasInduk,

  PasangPenangan,
  LepasPenangan,
  Lempar,
  LemparUlang,

  IteratorAwal,
  IteratorLanjut,
  KunciDalam,
  Hasilkan,
  Tunggu,

  MuatModul,
  ImporDinamis,
  Regex,

  LarikBaru,
  LarikTambah,
  LarikSebar,
  ObjekBaru,
  ObjekProp,
  ObjekPropDinamis,
  ObjekSebar,
  BacaProperti,
  BacaPropertiOpsional,
  TulisProperti,
  BacaIndeks,
  TulisIndeks,

  Cetak,

  IteratorAwalAsync,
  IteratorLanjutAsync,
}

export interface InfoOp {
  nama: string;
  operan: number;
}

export const INFO_OP: Record<Op, InfoOp> = {
  [Op.Konstanta]: { nama: "Konstanta", operan: 1 },
  [Op.Kosong]: { nama: "Kosong", operan: 0 },
  [Op.Taktentu]: { nama: "Taktentu", operan: 0 },
  [Op.Benar]: { nama: "Benar", operan: 0 },
  [Op.Salah]: { nama: "Salah", operan: 0 },
  [Op.Nol]: { nama: "Nol", operan: 0 },
  [Op.Satu]: { nama: "Satu", operan: 0 },
  [Op.Pop]: { nama: "Pop", operan: 0 },
  [Op.Gandakan]: { nama: "Gandakan", operan: 0 },
  [Op.Gandakan2]: { nama: "Gandakan2", operan: 0 },
  [Op.Tukar]: { nama: "Tukar", operan: 0 },
  [Op.TambahLokal]: { nama: "TambahLokal", operan: 0 },
  [Op.BacaLokal]: { nama: "BacaLokal", operan: 1 },
  [Op.TulisLokal]: { nama: "TulisLokal", operan: 1 },
  [Op.BacaGlobal]: { nama: "BacaGlobal", operan: 1 },
  [Op.TulisGlobal]: { nama: "TulisGlobal", operan: 1 },
  [Op.DefinisiGlobal]: { nama: "DefinisiGlobal", operan: 1 },
  [Op.BacaUpvalue]: { nama: "BacaUpvalue", operan: 1 },
  [Op.TulisUpvalue]: { nama: "TulisUpvalue", operan: 1 },
  [Op.TutupUpvalue]: { nama: "TutupUpvalue", operan: 0 },
  [Op.Tambah]: { nama: "Tambah", operan: 0 },
  [Op.Kurang]: { nama: "Kurang", operan: 0 },
  [Op.Kali]: { nama: "Kali", operan: 0 },
  [Op.Bagi]: { nama: "Bagi", operan: 0 },
  [Op.Sisa]: { nama: "Sisa", operan: 0 },
  [Op.Pangkat]: { nama: "Pangkat", operan: 0 },
  [Op.Negasi]: { nama: "Negasi", operan: 0 },
  [Op.Positif]: { nama: "Positif", operan: 0 },
  [Op.Dan]: { nama: "Dan", operan: 0 },
  [Op.Atau]: { nama: "Atau", operan: 0 },
  [Op.Xor]: { nama: "Xor", operan: 0 },
  [Op.Tilde]: { nama: "Tilde", operan: 0 },
  [Op.GeserKiri]: { nama: "GeserKiri", operan: 0 },
  [Op.GeserKanan]: { nama: "GeserKanan", operan: 0 },
  [Op.GeserKananNol]: { nama: "GeserKananNol", operan: 0 },
  [Op.SamaDengan]: { nama: "SamaDengan", operan: 0 },
  [Op.TidakSama]: { nama: "TidakSama", operan: 0 },
  [Op.KurangDari]: { nama: "KurangDari", operan: 0 },
  [Op.LebihDari]: { nama: "LebihDari", operan: 0 },
  [Op.KurangSamaDari]: { nama: "KurangSamaDari", operan: 0 },
  [Op.LebihSamaDari]: { nama: "LebihSamaDari", operan: 0 },
  [Op.Bukan]: { nama: "Bukan", operan: 0 },
  [Op.JenisDari]: { nama: "JenisDari", operan: 0 },
  [Op.ContohDari]: { nama: "ContohDari", operan: 0 },
  [Op.Dalam]: { nama: "Dalam", operan: 0 },
  [Op.Lompat]: { nama: "Lompat", operan: 1 },
  [Op.LompatJikaSalah]: { nama: "LompatJikaSalah", operan: 1 },
  [Op.LompatJikaBenar]: { nama: "LompatJikaBenar", operan: 1 },
  [Op.LompatBalik]: { nama: "LompatBalik", operan: 1 },
  [Op.Panggil]: { nama: "Panggil", operan: 1 },
  [Op.PanggilDenganIni]: { nama: "PanggilDenganIni", operan: 1 },
  [Op.Penutup]: { nama: "Penutup", operan: 1 },
  [Op.Kembali]: { nama: "Kembali", operan: 0 },
  [Op.LompatJikaKosong]: { nama: "LompatJikaKosong", operan: 1 },
  [Op.LompatJikaTaktentu]: { nama: "LompatJikaTaktentu", operan: 1 },
  [Op.LarikSisa]: { nama: "LarikSisa", operan: 1 },
  [Op.KelasBaru]: { nama: "KelasBaru", operan: 1 },
  [Op.WarisiKelas]: { nama: "WarisiKelas", operan: 0 },
  [Op.MetodeKelas]: { nama: "MetodeKelas", operan: 2 },
  [Op.FieldInstance]: { nama: "FieldInstance", operan: 1 },
  [Op.FieldStatis]: { nama: "FieldStatis", operan: 1 },
  [Op.JalankanStatis]: { nama: "JalankanStatis", operan: 0 },
  [Op.Konstruksi]: { nama: "Konstruksi", operan: 1 },
  [Op.PanggilInduk]: { nama: "PanggilInduk", operan: 1 },
  [Op.BacaIndukMetode]: { nama: "BacaIndukMetode", operan: 1 },
  [Op.SelesaikanKelasInduk]: { nama: "SelesaikanKelasInduk", operan: 0 },
  [Op.PasangPenangan]: { nama: "PasangPenangan", operan: 1 },
  [Op.LepasPenangan]: { nama: "LepasPenangan", operan: 0 },
  [Op.Lempar]: { nama: "Lempar", operan: 0 },
  [Op.LemparUlang]: { nama: "LemparUlang", operan: 0 },
  [Op.IteratorAwal]: { nama: "IteratorAwal", operan: 0 },
  [Op.IteratorLanjut]: { nama: "IteratorLanjut", operan: 0 },
  [Op.KunciDalam]: { nama: "KunciDalam", operan: 0 },
  [Op.Hasilkan]: { nama: "Hasilkan", operan: 0 },
  [Op.Tunggu]: { nama: "Tunggu", operan: 0 },
  [Op.MuatModul]: { nama: "MuatModul", operan: 1 },
  [Op.ImporDinamis]: { nama: "ImporDinamis", operan: 0 },
  [Op.Regex]: { nama: "Regex", operan: 2 },
  [Op.LarikBaru]: { nama: "LarikBaru", operan: 0 },
  [Op.LarikTambah]: { nama: "LarikTambah", operan: 0 },
  [Op.LarikSebar]: { nama: "LarikSebar", operan: 0 },
  [Op.ObjekBaru]: { nama: "ObjekBaru", operan: 0 },
  [Op.ObjekProp]: { nama: "ObjekProp", operan: 1 },
  [Op.ObjekPropDinamis]: { nama: "ObjekPropDinamis", operan: 0 },
  [Op.ObjekSebar]: { nama: "ObjekSebar", operan: 0 },
  [Op.BacaProperti]: { nama: "BacaProperti", operan: 1 },
  [Op.BacaPropertiOpsional]: { nama: "BacaPropertiOpsional", operan: 1 },
  [Op.TulisProperti]: { nama: "TulisProperti", operan: 1 },
  [Op.BacaIndeks]: { nama: "BacaIndeks", operan: 0 },
  [Op.TulisIndeks]: { nama: "TulisIndeks", operan: 0 },
  [Op.Cetak]: { nama: "Cetak", operan: 0 },
  [Op.IteratorAwalAsync]: { nama: "IteratorAwalAsync", operan: 0 },
  [Op.IteratorLanjutAsync]: { nama: "IteratorLanjutAsync", operan: 0 },
};
