export enum JenisToken {
  Angka = "Angka",
  BilanganBesar = "BilanganBesar",
  Teks = "Teks",
  TemplateUtuh = "TemplateUtuh",
  TemplateKepala = "TemplateKepala",
  TemplateTengah = "TemplateTengah",
  TemplateEkor = "TemplateEkor",
  Regex = "Regex",
  Identifier = "Identifier",
  PrivatNama = "PrivatNama",

  KurungBuka = "KurungBuka",
  KurungTutup = "KurungTutup",
  KurawalBuka = "KurawalBuka",
  KurawalTutup = "KurawalTutup",
  SikuBuka = "SikuBuka",
  SikuTutup = "SikuTutup",

  Koma = "Koma",
  TitikKoma = "TitikKoma",
  TitikDua = "TitikDua",
  Titik = "Titik",
  Elipsis = "Elipsis",
  Tanya = "Tanya",
  TanyaTitik = "TanyaTitik",
  Nullish = "Nullish",
  Panah = "Panah",

  Tambah = "Tambah",
  Kurang = "Kurang",
  Kali = "Kali",
  Bagi = "Bagi",
  Sisa = "Sisa",
  Pangkat = "Pangkat",
  TambahTambah = "TambahTambah",
  KurangKurang = "KurangKurang",

  SamaDengan = "SamaDengan",
  TambahSama = "TambahSama",
  KurangSama = "KurangSama",
  KaliSama = "KaliSama",
  BagiSama = "BagiSama",
  SisaSama = "SisaSama",
  PangkatSama = "PangkatSama",
  DanDanSama = "DanDanSama",
  AtauAtauSama = "AtauAtauSama",
  NullishSama = "NullishSama",
  DanSama = "DanSama",
  AtauSama = "AtauSama",
  XorSama = "XorSama",
  GeserKiriSama = "GeserKiriSama",
  GeserKananSama = "GeserKananSama",
  GeserKananNolSama = "GeserKananNolSama",

  SamaSama = "SamaSama",
  TidakSama = "TidakSama",
  SamaSamaSama = "SamaSamaSama",
  TidakSamaSama = "TidakSamaSama",
  KurangDari = "KurangDari",
  LebihDari = "LebihDari",
  KurangSamaDari = "KurangSamaDari",
  LebihSamaDari = "LebihSamaDari",

  DanDan = "DanDan",
  AtauAtau = "AtauAtau",
  Seru = "Seru",

  Dan = "Dan",
  Atau = "Atau",
  Xor = "Xor",
  Tilde = "Tilde",
  GeserKiri = "GeserKiri",
  GeserKanan = "GeserKanan",
  GeserKananNol = "GeserKananNol",

  KkMisal = "KkMisal",
  KkTetap = "KkTetap",
  KkVar = "KkVar",
  KkJika = "KkJika",
  KkLainnya = "KkLainnya",
  KkPilih = "KkPilih",
  KkKasus = "KkKasus",
  KkBawaan = "KkBawaan",
  KkSelama = "KkSelama",
  KkLakukan = "KkLakukan",
  KkUntuk = "KkUntuk",
  KkDari = "KkDari",
  KkDalam = "KkDalam",
  KkHenti = "KkHenti",
  KkLanjut = "KkLanjut",
  KkFungsi = "KkFungsi",
  KkKembalikan = "KkKembalikan",
  KkHasilkan = "KkHasilkan",
  KkAsinkron = "KkAsinkron",
  KkTunggu = "KkTunggu",
  KkBenar = "KkBenar",
  KkSalah = "KkSalah",
  KkKosong = "KkKosong",
  KkTaktentu = "KkTaktentu",
  KkKelas = "KkKelas",
  KkBaru = "KkBaru",
  KkIni = "KkIni",
  KkInduk = "KkInduk",
  KkMewarisi = "KkMewarisi",
  KkKonstruktor = "KkKonstruktor",
  KkStatis = "KkStatis",
  KkDapatkan = "KkDapatkan",
  KkTetapkan = "KkTetapkan",
  KkCoba = "KkCoba",
  KkTangkap = "KkTangkap",
  KkAkhirnya = "KkAkhirnya",
  KkLempar = "KkLempar",
  KkImpor = "KkImpor",
  KkEkspor = "KkEkspor",
  KkSebagai = "KkSebagai",
  KkJenisdari = "KkJenisdari",
  KkContohdari = "KkContohdari",
  KkHapus = "KkHapus",
  KkAbaikan = "KkAbaikan",

  AkhirBerkas = "AkhirBerkas",
}

export interface Token {
  jenis: JenisToken;
  teks: string;
  baris: number;
  kolom: number;
  awal: number;
  akhir: number;
  didahuluiBarisBaru: boolean;
}

export const KATA_KUNCI: ReadonlyMap<string, JenisToken> = new Map([
  ["misal", JenisToken.KkMisal],
  ["tetap", JenisToken.KkTetap],
  ["var", JenisToken.KkVar],
  ["jika", JenisToken.KkJika],
  ["lainnya", JenisToken.KkLainnya],
  ["pilih", JenisToken.KkPilih],
  ["kasus", JenisToken.KkKasus],
  ["bawaan", JenisToken.KkBawaan],
  ["selama", JenisToken.KkSelama],
  ["lakukan", JenisToken.KkLakukan],
  ["untuk", JenisToken.KkUntuk],
  ["dari", JenisToken.KkDari],
  ["dalam", JenisToken.KkDalam],
  ["henti", JenisToken.KkHenti],
  ["lanjut", JenisToken.KkLanjut],
  ["fungsi", JenisToken.KkFungsi],
  ["kembalikan", JenisToken.KkKembalikan],
  ["hasilkan", JenisToken.KkHasilkan],
  ["asinkron", JenisToken.KkAsinkron],
  ["tunggu", JenisToken.KkTunggu],
  ["benar", JenisToken.KkBenar],
  ["salah", JenisToken.KkSalah],
  ["kosong", JenisToken.KkKosong],
  ["taktentu", JenisToken.KkTaktentu],
  ["dan", JenisToken.DanDan],
  ["atau", JenisToken.AtauAtau],
  ["bukan", JenisToken.Seru],
  ["kelas", JenisToken.KkKelas],
  ["baru", JenisToken.KkBaru],
  ["ini", JenisToken.KkIni],
  ["induk", JenisToken.KkInduk],
  ["mewarisi", JenisToken.KkMewarisi],
  ["konstruktor", JenisToken.KkKonstruktor],
  ["statis", JenisToken.KkStatis],
  ["dapatkan", JenisToken.KkDapatkan],
  ["tetapkan", JenisToken.KkTetapkan],
  ["coba", JenisToken.KkCoba],
  ["tangkap", JenisToken.KkTangkap],
  ["akhirnya", JenisToken.KkAkhirnya],
  ["lempar", JenisToken.KkLempar],
  ["impor", JenisToken.KkImpor],
  ["ekspor", JenisToken.KkEkspor],
  ["sebagai", JenisToken.KkSebagai],
  ["jenisdari", JenisToken.KkJenisdari],
  ["contohdari", JenisToken.KkContohdari],
  ["hapus", JenisToken.KkHapus],
  ["abaikan", JenisToken.KkAbaikan],
]);

export const KATA_KUNCI_LUNAK: ReadonlySet<JenisToken> = new Set([
  JenisToken.KkDari,
  JenisToken.KkSebagai,
  JenisToken.KkDapatkan,
  JenisToken.KkTetapkan,
  JenisToken.KkStatis,
  JenisToken.KkKonstruktor,
  JenisToken.KkBawaan,
]);

const NAMA_TAMPIL: Partial<Record<JenisToken, string>> = {
  [JenisToken.KurungBuka]: "(",
  [JenisToken.KurungTutup]: ")",
  [JenisToken.KurawalBuka]: "{",
  [JenisToken.KurawalTutup]: "}",
  [JenisToken.SikuBuka]: "[",
  [JenisToken.SikuTutup]: "]",
  [JenisToken.Koma]: ",",
  [JenisToken.TitikKoma]: ";",
  [JenisToken.TitikDua]: ":",
  [JenisToken.Titik]: ".",
  [JenisToken.SamaDengan]: "=",
  [JenisToken.AkhirBerkas]: "akhir berkas",
};

export function namaTampilToken(jenis: JenisToken): string {
  return NAMA_TAMPIL[jenis] ?? jenis;
}
